// Code generated by Slice Machine. DO NOT EDIT.

import Header from "./Header/index.svelte";
import Programs from "./Programs/index.svelte";

export const components = {
  header: Header,
  programs: Programs,
};
