// Code generated by Slice Machine. DO NOT EDIT.

import Activities from "./Activities/index.svelte";
import Batch from "./Batch/index.svelte";
import Blog from "./Blog/index.svelte";
import Card from "./Card/index.svelte";
import Carousel from "./Carousel/index.svelte";
import Counter from "./Counter/index.svelte";
import Gallery from "./Gallery/index.svelte";
import Header from "./Header/index.svelte";
import Hero from "./Hero/index.svelte";
import Pride from "./Pride/index.svelte";
import Programs from "./Programs/index.svelte";
import Team from "./Team/index.svelte";
import Testimonials from "./Testimonials/index.svelte";

export const components = {
  activities: Activities,
  batch: Batch,
  blogs: Blog,
  card: Card,
  carousel: Carousel,
  counter: Counter,
  gallery: Gallery,
  header: Header,
  hero: Hero,
  pride: Pride,
  programs: Programs,
  team: Team,
  testimonials: Testimonials,
};
