// Code generated by Slice Machine. DO NOT EDIT.

import Activities from "./Activities/index.svelte";
import Header from "./Header/index.svelte";
import Programs from "./Programs/index.svelte";

export const components = {
  activities: Activities,
  header: Header,
  programs: Programs,
};
